// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: stat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewRequest) Reset() {
	*x = OverviewRequest{}
	mi := &file_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewRequest) ProtoMessage() {}

func (x *OverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewRequest.ProtoReflect.Descriptor instead.
func (*OverviewRequest) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{0}
}

type OverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PvToday       int64                  `protobuf:"varint,1,opt,name=pv_today,json=pvToday,proto3" json:"pv_today,omitempty"`
	UvToday       int64                  `protobuf:"varint,2,opt,name=uv_today,json=uvToday,proto3" json:"uv_today,omitempty"`
	OnlineUsers   int64                  `protobuf:"varint,3,opt,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewResponse) Reset() {
	*x = OverviewResponse{}
	mi := &file_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewResponse) ProtoMessage() {}

func (x *OverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewResponse.ProtoReflect.Descriptor instead.
func (*OverviewResponse) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{1}
}

func (x *OverviewResponse) GetPvToday() int64 {
	if x != nil {
		return x.PvToday
	}
	return 0
}

func (x *OverviewResponse) GetUvToday() int64 {
	if x != nil {
		return x.UvToday
	}
	return 0
}

func (x *OverviewResponse) GetOnlineUsers() int64 {
	if x != nil {
		return x.OnlineUsers
	}
	return 0
}

type PVTimeSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVTimeSeriesRequest) Reset() {
	*x = PVTimeSeriesRequest{}
	mi := &file_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVTimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVTimeSeriesRequest) ProtoMessage() {}

func (x *PVTimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVTimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*PVTimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{2}
}

func (x *PVTimeSeriesRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PVTimeSeriesRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PVTimeSeriesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{3}
}

func (x *Point) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Point) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PVTimeSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVTimeSeriesResponse) Reset() {
	*x = PVTimeSeriesResponse{}
	mi := &file_stat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVTimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVTimeSeriesResponse) ProtoMessage() {}

func (x *PVTimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVTimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*PVTimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{4}
}

func (x *PVTimeSeriesResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_stat_proto protoreflect.FileDescriptor

const file_stat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"stat.proto\x12\x04stat\"\x11\n" +
	"\x0fOverviewRequest\"k\n" +
	"\x10OverviewResponse\x12\x19\n" +
	"\bpv_today\x18\x01 \x01(\x03R\apvToday\x12\x19\n" +
	"\buv_today\x18\x02 \x01(\x03R\auvToday\x12!\n" +
	"\fonline_users\x18\x03 \x01(\x03R\vonlineUsers\"U\n" +
	"\x13PVTimeSeriesRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\"-\n" +
	"\x05Point\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\";\n" +
	"\x14PVTimeSeriesResponse\x12#\n" +
	"\x06points\x18\x01 \x03(\v2\v.stat.PointR\x06points2\x8f\x01\n" +
	"\vStatService\x129\n" +
	"\bOverview\x12\x15.stat.OverviewRequest\x1a\x16.stat.OverviewResponse\x12E\n" +
	"\fPVTimeSeries\x12\x19.stat.PVTimeSeriesRequest\x1a\x1a.stat.PVTimeSeriesResponseB!Z\x1fblog-system/services/stat/protob\x06proto3"

var (
	file_stat_proto_rawDescOnce sync.Once
	file_stat_proto_rawDescData []byte
)

func file_stat_proto_rawDescGZIP() []byte {
	file_stat_proto_rawDescOnce.Do(func() {
		file_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stat_proto_rawDesc), len(file_stat_proto_rawDesc)))
	})
	return file_stat_proto_rawDescData
}

var file_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stat_proto_goTypes = []any{
	(*OverviewRequest)(nil),      // 0: stat.OverviewRequest
	(*OverviewResponse)(nil),     // 1: stat.OverviewResponse
	(*PVTimeSeriesRequest)(nil),  // 2: stat.PVTimeSeriesRequest
	(*Point)(nil),                // 3: stat.Point
	(*PVTimeSeriesResponse)(nil), // 4: stat.PVTimeSeriesResponse
}
var file_stat_proto_depIdxs = []int32{
	3, // 0: stat.PVTimeSeriesResponse.points:type_name -> stat.Point
	0, // 1: stat.StatService.Overview:input_type -> stat.OverviewRequest
	2, // 2: stat.StatService.PVTimeSeries:input_type -> stat.PVTimeSeriesRequest
	1, // 3: stat.StatService.Overview:output_type -> stat.OverviewResponse
	4, // 4: stat.StatService.PVTimeSeries:output_type -> stat.PVTimeSeriesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stat_proto_init() }
func file_stat_proto_init() {
	if File_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stat_proto_rawDesc), len(file_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stat_proto_goTypes,
		DependencyIndexes: file_stat_proto_depIdxs,
		MessageInfos:      file_stat_proto_msgTypes,
	}.Build()
	File_stat_proto = out.File
	file_stat_proto_goTypes = nil
	file_stat_proto_depIdxs = nil
}
