app:
  name: content-service
  port: 8002

database:
  driver: "mysql"
  host: 172.21.87.206
  port: 3306
  user: root
  password: BLOG_PASSWORD
  name: blog_system

redis:
  cluster:
    addrs:
      - "127.0.0.1:7001"
      - "127.0.0.1:7002"
      - "127.0.0.1:7003"
    password: ""
    pool_size: 10
    min_idle_conns: 5
    max_retries: 3
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"

registry:
  endpoints:
    - "http://127.0.0.1:2379"

log:
  level: info
  path: logs/content-service.log

