app:
  name: gateway-service
  port: 8000

# 路由配置
routes:
  # 用户服务路由
  user:
    prefix: "/api/user"
    target: "service://user-service"
    timeout: "30s"
    retries: 3
  # 内容服务路由
  content:
    prefix: "/api/content"
    target: "http://localhost:8002"
    timeout: "30s"
    retries: 3
  # 评论服务路由
  comment:
    prefix: "/api/comment"
    target: "http://localhost:8003"
    timeout: "30s"
    retries: 3
  # 统计服务路由
  stat:
    prefix: "/api/stat"
    target: "http://localhost:8004"
    timeout: "30s"
    retries: 3
  # 管理服务路由
  admin:
    prefix: "/api/admin"
    target: "http://localhost:8005"
    timeout: "30s"
    retries: 3

# 限流配置
rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 200

# 熔断配置
circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout: "60s"

# Redis Cluster配置 - 用于限流和缓存
redis:
  cluster:
    addrs:
      - "127.0.0.1:7001"
      - "127.0.0.1:7002"
      - "127.0.0.1:7003"
    password: ""
    pool_size: 10
    min_idle_conns: 5
    max_retries: 3
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"

# 日志配置
registry:
  endpoints:
    - "http://127.0.0.1:2379"

log:
  level: info
  path: logs/gateway.log 