app:
  name: stat-service
  port: 8004

grpc:
  port: 9004

database:
  driver: "mysql"
  host: 172.21.87.206
  port: 3306
  user: root
  password: BLOG_PASSWORD
  name: blog_system

registry:
  endpoints:
    - "http://127.0.0.1:2379"

# Prometheus（可选）：默认 http://localhost:9090
prometheus:
  address: "http://localhost:9090"

log:
  level: debug
  path: logs/stat-service.log

