app:
  name: user-service
  port: 8001

database:
  driver: "mysql"
  host: localhost
  port: 3306
  user: root
  password: BLOG_PASSWORD
  name: blog_system

redis:
  # Redis Cluster配置 - 生产环境使用集群模式
  cluster:
    addrs:
      - "127.0.0.1:7001"
      - "127.0.0.1:7002"
      - "127.0.0.1:7003"
    password: ""
    # 集群配置选项
    pool_size: 10
    min_idle_conns: 5
    max_retries: 3
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"

grpc:
  port: 9001

registry:
  endpoints:
    - "http://127.0.0.1:2379"

log:
  level: debug
  # 实际路径由部署脚本决定
  path: logs/user-service.log