name: Deploy Blog System

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 部署公共模块
  deploy-common:
    runs-on: ubuntu-latest
    outputs:
      common-deployed: ${{ steps.deploy-common.outputs.success }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy common module
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -euo pipefail
          exec 2>&1
          mkdir -p /opt/blog-system
          rm -rf /opt/blog-system/common
          
    - name: Upload common files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "common"
        target: /opt/blog-system
        
    - name: Verify common module
      uses: appleboy/ssh-action@v0.1.5
      id: deploy-common
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -euo pipefail
          exec 2>&1
          cd /opt/blog-system/common
          if [ -f "go.mod" ]; then
            echo "Common module deployed successfully"
            echo "::set-output name=success::true"
          else
            echo "Common module deployment failed"
            exit 1
          fi

  # 部署用户服务
  deploy-user-service:
    runs-on: ubuntu-latest
    needs: deploy-common
    outputs:
      user-deployed: ${{ steps.deploy-user.outputs.success }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy user service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -euo pipefail
          exec 2>&1
          mkdir -p /opt/blog-system
          systemctl stop user-service || true
          rm -rf /opt/blog-system/services/user /opt/blog-system/configs/user.yaml
          
    - name: Upload user service files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "services/user,configs/user.yaml"
        target: /opt/blog-system
        
    - name: Execute user service deployment
      uses: appleboy/ssh-action@v0.1.5
      id: deploy-user
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: BLOG_PASSWORD
        script: |
          set -euo pipefail
          exec 2>&1
          cd /opt/blog-system
          export BLOG_PASSWORD="${{ secrets.BLOG_PASSWORD }}"
          chmod +x deploy/deploy-user-service.sh
          ./deploy/deploy-user-service.sh
          echo "::set-output name=success::true"
          
    - name: Verify user service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -euo pipefail
          exec 2>&1
          sleep 10
          if systemctl is-active --quiet user-service; then
            echo "User service deployed successfully"
          else
            echo "User service deployment failed"
            systemctl status user-service --no-pager -l
            exit 1
          fi

  # 部署网关服务
  deploy-gateway-service:
    runs-on: ubuntu-latest
    needs: deploy-user-service
    outputs:
      gateway-deployed: ${{ steps.deploy-gateway.outputs.success }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Check user service dependency
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -euo pipefail
          exec 2>&1
          # 检查用户服务是否运行
          if ! systemctl is-active --quiet user-service; then
            echo "User service is not running. Please deploy user service first."
            exit 1
          fi
          
          # 检查用户服务端口
          if ! netstat -tlnp | grep -q ":8001"; then
            echo "User service port 8001 is not listening. Please check user service."
            exit 1
          fi
          
          echo "User service dependency check passed"
          
    - name: Deploy gateway service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -euo pipefail
          exec 2>&1
          mkdir -p /opt/blog-system
          systemctl stop gateway-service || true
          rm -rf /opt/blog-system/services/gateway /opt/blog-system/configs/gateway.yaml
          
    - name: Upload gateway service files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "services/gateway,configs/gateway.yaml"
        target: /opt/blog-system
        
    - name: Execute gateway service deployment
      uses: appleboy/ssh-action@v0.1.5
      id: deploy-gateway
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: BLOG_PASSWORD
        script: |
          set -euo pipefail
          exec 2>&1
          cd /opt/blog-system
          export BLOG_PASSWORD="${{ secrets.BLOG_PASSWORD }}"
          chmod +x deploy/deploy-gateway-service.sh
          ./deploy/deploy-gateway-service.sh
          echo "::set-output name=success::true"
          
    - name: Verify gateway service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -euo pipefail
          exec 2>&1
          sleep 10
          if systemctl is-active --quiet gateway-service; then
            echo "Gateway service deployed successfully"
          else
            echo "Gateway service deployment failed"
            systemctl status gateway-service --no-pager -l
            exit 1
          fi 