name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24.2'
        
    - name: Build application
      run: |
        cd services/user
        go mod download
        go build -o user-service .
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # 创建部署目录
          mkdir -p /opt/blog-system
          
          # 停止现有服务
          systemctl stop user-service || true
          
          # 清理旧文件
          rm -rf /opt/blog-system/services /opt/blog-system/configs /opt/blog-system/deploy /opt/blog-system/common
          
    - name: Upload files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "services,configs,deploy,common"
        target: /opt/blog-system
        
    - name: Execute deployment script
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: BLOG_PASSWORD
        script: |
          cd /opt/blog-system
          
          # 设置环境变量
          export BLOG_PASSWORD="${{ secrets.BLOG_PASSWORD }}"
          
          # 给部署脚本执行权限
          chmod +x deploy/deploy.sh
          
          # 执行部署脚本
          ./deploy/deploy.sh
          
          # 等待服务启动
          sleep 15
          
          # 检查服务状态
          systemctl status user-service --no-pager -l
          
          # 检查端口监听
          netstat -tlnp | grep :8001 || echo "端口8001未监听"
          
          # 健康检查
          curl -f http://localhost:8001/health || echo "健康检查失败" 