name: Deploy User Service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/user/**'
      - 'common/**'
      - 'configs/user.yaml'
      - '.github/workflows/deploy-user-service.yml'
  workflow_dispatch:

jobs:
  deploy-user-service:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy user service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p /opt/blog-system
          systemctl stop user-service || true
          rm -rf /opt/blog-system/services/user /opt/blog-system/configs/user.yaml
          
    - name: Upload user service files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "services/user,configs/user.yaml"
        target: /opt/blog-system
        
    - name: Execute user service deployment
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: BLOG_PASSWORD
        script: |
          cd /opt/blog-system
          export BLOG_PASSWORD="${{ secrets.BLOG_PASSWORD }}"
          chmod +x deploy/deploy.sh
          # 只部署用户服务
          ./deploy/deploy-user-service.sh
          
    - name: Verify user service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sleep 10
          if systemctl is-active --quiet user-service; then
            echo "User service deployed successfully"
          else
            echo "User service deployment failed"
            systemctl status user-service --no-pager -l
            exit 1
          fi 